# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CID',
            field=models.IntegerField(null=True),
        ),
    ]
