# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 23:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0002_user_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateField(default=datetime.date(1977, 7, 25)),
        ),
    ]
