# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-04 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0003_auto_20160913_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('A', 'Admin'), ('S', 'Standard'), ('N', 'Non Active')], max_length=1),
        ),
    ]
