# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0005_auto_20161017_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_rank',
            field=models.CharField(choices=[('BSc', 'Under graduate'), ('MSc', 'MSC student'), ('PhD', 'PhD student'), ('Staff', 'Academic staff'), ('Other', 'Other')], default='other', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('A', 'Lab admin'), ('S', 'User'), ('N', 'Non Active')], default='User', max_length=1),
        ),
    ]
