# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0007_auto_20161017_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_rank',
        ),
    ]
