# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0010_auto_20161017_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_rank',
        ),
    ]
