# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0011_remove_user_user_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('user_rank', 'name')},
        ),
        migrations.AddField(
            model_name='user',
            name='user_rank',
            field=models.CharField(choices=[('BSc', 'Under graduate'), ('MSc', 'MSC student'), ('PhD', 'PhD student'), ('Staff', 'Academic staff'), ('Other', 'Other')], default='Other', max_length=1),
        ),
    ]
