# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0012_auto_20161017_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_rank',
            field=models.CharField(choices=[('BSc', 'Under graduate'), ('MSc', 'MSC student'), ('PhD', 'PhD student'), ('Staff', 'Academic staff'), ('Other', 'other')], default='other', max_length=1),
        ),
    ]
