# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 22:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_list', '0018_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('supervisor', models.CharField(max_length=30)),
                ('user_type', models.CharField(choices=[('A', 'Lab admin'), ('S', 'User'), ('N', 'Non Active')], default='User', max_length=1)),
                ('user_rank', models.CharField(choices=[('BSc', 'Under graduate'), ('MSc', 'MSC student'), ('PhD', 'PhD student'), ('Staff', 'Academic staff'), ('Other', 'Other')], default='Other', max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('join_date', models.DateField(default=datetime.date(1977, 7, 25))),
                ('CID', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ('user_rank', 'name'),
            },
        ),
    ]
