# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-10 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0021_auto_20161018_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_rank',
            field=models.CharField(choices=[('UG', 'Under graduate'), ('MSc', 'MSC student'), ('PhD', 'PhD student'), ('Staff', 'Staff'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
