# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-20 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0022_auto_20161110_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NA', 'Non Active'), ('Active', 'Active'), ('New User', 'New')], default='Active', max_length=8),
        ),
    ]
